# Generated by Django 4.0.4 on 2022-05-01 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_user_email'),
        ('posts', '0003_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='host_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
