# Generated by Django 4.0.4 on 2022-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupprofile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='is_feed',
            field=models.BooleanField(default=False),
        ),
    ]
