# Generated by Django 4.0.4 on 2022-05-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupprofile_is_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='name',
            field=models.TextField(default='Feed'),
        ),
    ]
